export * from './StyledTextCom'
export * from './StyledGlobal'
export * from './StyledHeaderCom'
export * from './StyledCategory'
export * from './StyledCardCom'
export * from './StyledCart'
export * from './StyledOrderCard'
export * from './StyledModal'